sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
before_install:
  - npm config set registry https://:2016-08-08T17%3A45%3A22.959000Z@time-machines-npm.sealsecurity.io/
dist: precise
